# steps:
# - name: python:latest
#   args: ['python3','/workspace/main.py']
# - name: ubuntu
#   args: ['ls','/']

steps:
  - name: python:latest
    args: ['python3','main.py']
    id: 'build'
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zip', '.']
  images: ['gcr.io/$PROJECT_ID/zip']
  - name: gcr.io/$PROJECT_ID/zip
    args: ['code-$BUILD_ID.zip','./*.py']
  # - name: ubuntu
  #   args: ['zip','-r','code.zip','./*.py']
  #   id: 'zipp'
  - name: google/cloud-sdk:latest
    args: ['gsutil','cp','code-$BUILD_ID.zip','gs://dummy_use/cloudbuild-$BUILD_ID/']
    waitFor: ['build']

    
    
