steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','${_LOCATION}/$PROJECT_ID/${_REPO}/${_IMG}','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','${_LOCATION}/$PROJECT_ID/${_REPO}/${_IMG}']
  - name: '${IMAGE}'
    args: ['dfpipeline.py']

substitutions:
_LOCATION: us-central1-docker.pkg.dev
_REPO: dataflow-images
_IMG: dataflow_img:v1
