# steps:
# - name: python:latest
#   args: ['python3','/workspace/main.py']
# - name: ubuntu
#   args: ['ls','/']

steps:
  - name: python:latest
    args: ['python3','main.py']
    id: 'build'
  - name: ubuntu
    args: ['zip','-r','code.zip','./*.py']
    id: 'zipp'
  - name: google/cloud-sdk:latest
    args: ['gsutil','cp','code.zip','gs://dummy_use/cloudbuild1/']
    waitFor: ['build']

    
    
