# steps:
#   - name: python:latest
#     args: ['python3','main.py']
#     id: 'build'
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build','-t','gcr.io/$PROJECT_ID/zip','.']
#   images: ['gcr.io/$PROJECT_ID/zip']
#   - name: 'gcr.io/$PROJECT_ID/zip'
#     args: ['code-$BUILD_ID.zip','./*.py']
#     id: 'zip' 
#   - name: 'google/cloud-sdk:latest'
#     args: ['gsutil','cp','code-$BUILD_ID.zip','gs://dummy_use/cloudbuild-$BUILD_ID/']
#     waitFor: ['build','zip']
--- 
steps: 
  - 
    args: 
      - python3
      - main.py
    id: build
    name: "python:latest"
  - 
    args: 
      - build
      - "-t"
      - gcr.io/$PROJECT_ID/zip
      - "."
  images: 
    - gcr.io/$PROJECT_ID/zip
    name: gcr.io/cloud-builders/docker
  - 
    args: 
      - code-$BUILD_ID.zip
      - ./*.py
    id: zip
    name: gcr.io/$PROJECT_ID/zip
  - 
    args: 
      - gsutil
      - cp
      - code-$BUILD_ID.zip
      - "gs://dummy_use/cloudbuild-$BUILD_ID/"
    name: "google/cloud-sdk:latest"
    waitFor: 
      - build
      - zip
