# steps:
# - name: python:latest
#   args: ['python3','/workspace/main.py']
# - name: ubuntu
#   args: ['ls','/']

steps:
  - name: python:latest
    args: ['python3','1main.py']
  - name: ubuntu
    args: ['ls']  

    
    
