steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','-t','${_IMAGE}','.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']
  - name: '${IMAGE}'
    args: ['dfpipeline.py']

substitutions:
_IMAGE: us-central1-docker.pkg.dev/dataflow-images/dataflow_img:v1
